### ISSUE TITLE
Save extracted data into MongoDB

### ISSUE THREAD

**Issue by StanleySathler** [covid-19-unibh/crawler#2]
Our crawler extracts data from a table. This data must be saved into a MongoDB instance so that our API can consume it.

As per discussed before, the document must meet the following scheme:

```javascript
{
  neighborhood: String
  serious: Number
  nonSerious: Number
  deaths: Number
}
```

**Comment by paulotrindade1** [comment]
Data inserted like the image below

![image](https://user-images.githubusercontent.com/38356326/85933123-c312e280-b8a9-11ea-9ed3-1a206b7dd458.png)
